grid_map:
  ros__parameters:
    grid_map/x_size: 40.0
    grid_map/y_size: 20.0
    grid_map/z_size: 5.0
    grid_map/local_update_range_x: 40.0
    grid_map/local_update_range_y: 20.0
    grid_map/local_update_range_z: 5.0
    grid_map/obstacles_inflation: 0.099
    grid_map/resolution: 0.1
    grid_map/local_map_margin: 10
    grid_map/visualization_truncate_height: 2.0