random_forest:
  ros__parameters:
    init_state_x: -20.0
    init_state_y: 0.0
    map/x_size: 40
    map/y_size: 20
    map/column_num: 50
    map/circle_num: 30
    obstacle_shape/lower_rad: 0.5
    obstacle_shape/upper_rad: 0.7
    obstacle_shape/lower_height: 0.0
    obstacle_shape/upper_height: 8.0
    obstacle_shape/radius_l: 0.8
    obstacle_shape/radius_h: 0.5
    obstacle_shape/z_l: 2.7
    obstacle_shape/z_h: 2.8
    obstacle_shape/theta: 0.6
    sensing/radius: 50